In [38]:
import pandas as pd
df = pd.read_csv('C:/Users/saifm/Downloads/Compressed/archive_3/preprocessed_kindle_review .csv')
df.head()

,Unnamed: 0,rating,reviewText,summary
0,0,5,This book was the very first bookmobile book I...,50 + years ago...
1,1,1,"When I read the description for this book, I c...",Boring! Boring! Boring!
2,2,5,I just had to edit this review. This book is a...,Wiggleliscious/new toy ready/!!
3,3,5,I don't normally buy 'mystery' novels because ...,Very good read.
4,4,5,"This isn't the kind of book I normally read, a...",Great Story!

In [41]:
data = df[['reviewText', 'sentiment_label']]
data.head()

                                          reviewText sentiment_label
0  This book was the very first bookmobile book I...        positive
1  When I read the description for this book, I c...         neutral
2  I just had to edit this review. This book is a...        positive
3  I don't normally buy 'mystery' novels because ...        positive
4  This isn't the kind of book I normally read, a...        positive

In [56]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer

# Define the mapping function
def map_sentiment(score):
    if score == 0:
        return 'negative'
    elif 1 <= score <= 3:
        return 'neutral'
    elif 4 <= score <= 5:
        return 'positive'
    else:
        return 'unknown'  # Handle any unexpected values

# Load the dataset
df = pd.read_csv('C:/Users/saifm/Downloads/Compressed/archive_3/preprocessed_kindle_review .csv')

# Apply the mapping function
df['sentiment_label'] = df['rating'].apply(map_sentiment)

# Feature extraction
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(df['reviewText'])  # Assuming 'review_text' is your text column
y = df['sentiment_label']

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

# Initialize the classifier
model = MultinomialNB()

# Train the model
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.8225
Classification Report:
               precision    recall  f1-score   support

     neutral       0.82      0.83      0.83      2413
    positive       0.83      0.81      0.82      2387

    accuracy                           0.82      4800
   macro avg       0.82      0.82      0.82      4800
weighted avg       0.82      0.82      0.82      4800